// ==UserScript==
// @name         Local Debug Loader
// @namespace    https://github.com/wuyaos/greasyfork_scripts
// @version      0.1.0
// @description  通过本地 HTTP 文件服务器加载仓库里的 IYUU 与 MoviePilot 脚本，方便外部编辑器实时调试。
// @author       wuya
// @match        https://*/details.php?id=*
// @match        http://*/details.php?id=*
// @match        https://*/details_movie.php?id=*
// @match        https://*/details_tv.php?id=*
// @match        https://*/details_animate.php?id=*
// @match        https://totheglory.im/t/*
// @match        https://hdsky.me/details.php?id=*
// @match        https://pt.sjtu.edu.cn/details.php?id=*
// @match        https://bangumi.moe/*
// @match        https://mikanani.me/Home/*
// @match        https://*.comicat.org/*
// @match        https://comicat.org/*
// @match        http://*.comicat.org/*
// @match        http://comicat.org/*
// @match        https://*.m-team.cc/detail/*
// @match        https://*.m-team.io/detail/*
// @match        https://*.m-team.vip/detail/*
// @match        https://hdcity.city/t-*
// @match        https://greatposterwall.com/torrents.php*
// @match        https://iptorrents.com/torrent.php*
// @match        https://beyond-hd.me/torrents/*
// @match        https://filelist.io/details.php?id=*
// @match        https://monikadesign.uk/torrents/*
// @match        https://acg.rip/*
// @match        https://nyaa.si/*
// @match        https://*.kisssub.org/*
// @match        https://kisssub.org/*
// @match        http://*.kisssub.org/*
// @match        http://kisssub.org/*
// @grant        GM_log
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_deleteValue
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// @grant        GM_openInTab
// @grant        GM_setClipboard
// @grant        GM_info
// @connect      self
// @connect      127.0.0.1
// @connect      localhost
// @connect      2025.iyuu.cn
// @connect      zmpt.cc
// @connect      bangumi.moe
// @connect      api.m-team.cc
// @connect      api.m-team.io
// @connect      api.m-team.vip
// @connect      *.m-team.cc
// @connect      *.m-team.io
// @connect      *.m-team.vip
// @connect      halomt.com
// @connect      *
// @require      http://127.0.0.1:8787/IYUU_Reseed_Checker.user.js
// @require      http://127.0.0.1:8787/Moviepilot_NameTest.user.js
// @run-at       document-idle
// ==/UserScript==
